jobs:
  - name: dv-man-vr-test
    type: manifest
    steps:
      - IN: dv-image-vr-test
        pull: false
      - IN: dv-opts-vr-test
      - IN: dv-params-vr-test
        applyTo:
          - dv-image-vr-test
      
    on_success:
      - echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - echo 'this is on_failure step of dv-man of type manifest'
  
  - name: box-man-vr-test
    type: manifest
    steps:
      - IN: box-image
        pull: false
      
  
